name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Fix permissions for postgres_data
        run: |
            cd app
            sudo mkdir -p postgres_data
            sudo chmod -R 777 postgres_data
      - uses: actions/checkout@v3
      - name: Start database
        run: |
          cd app
          docker-compose up -d postgres
      - name: Run tests
        run: |
          cd app
          docker-compose run --rm tests
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
      - name: Run Flake8
        run: flake8 app/ --exit-zero